services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /home/chemistry/database:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "chemistry"
      POSTGRES_USER: "chemistry"
      POSTGRES_PASSWORD: "chemistry"
    networks:
      database:

  ingress:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      ingress:

  frontend:
    build: .
    restart: always
    networks:
      ingress:

  backend:
    build: ./backend
    restart: always
    networks:
      database:
      ingress:

networks:
  database:
  ingress:
